version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${DOCKER_MACHINE_IP}
      - KAFKA_ADVERTISED_PORT=9092
      - BROKER_ID=1
      - ZK_HOSTS=zookeeper:2181
      - AUTO_CREATE_TOPICS=true
      - DEFAULT_REPLICATION_FACTOR=1
      - NUM_PARTITIONS=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    tty: true
  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - $PWD/db-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
